version: 2.1

jobs:
  build:
    working_directory: ~/ExampleApplication
    docker:
      - image: cimg/node:10.16.3   # Using a Node.js Docker image
    steps:
      - checkout  # This checks out the code from the repository
      - run:
          name: Update npm to version 5
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}  # Caching dependencies based on package-lock.json
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}  # Saving the node_modules cache
          paths:
            - ./node_modules

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main  # Trigger the pipeline only for changes to the 'main' branch       

